spring:
  main:
    banner-mode: off    
bio-match:
  # define the left offset count
  left: 1
  # define the right offset count
  right: 1
  # if enable include the content in square brackets 
  include: true
  # if enable boundary check set true, otherwise set false
  boundary: true
  # set dna file path
  dnaFile: "./sample/CircRNA序列.xlsx"
  # set protein file path
  proteinFile: "./sample/质谱检测到的肽段-peptide1.xlsx"
  # set the output file path
  outputFile: "./output.txt"
  